// <auto-generated />
namespace Dexpa.WebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Update001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update001));
        
        string IMigrationMetadata.Id
        {
            get { return "201408170421450_Update001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
